import React, { useState } from 'react';
import { X, Sparkles, Download, Wand2, Play, Loader2, RefreshCw } from 'lucide-react';
import { toast } from 'react-hot-toast';
import axios from 'axios';

interface NoteAnalysisModalProps {
    note: any;
    analysis: any;
    onClose: () => void;
    onSelect?: (note: any) => void;
    onRefreshAnalysis?: (noteId: string) => Promise<void>;
}

const NoteAnalysisModal: React.FC<NoteAnalysisModalProps> = ({ note, analysis, onClose, onSelect, onRefreshAnalysis }) => {
    const [analyzing, setAnalyzing] = useState(false);

    const handleExportAnalysis = () => {
        if (!analysis || !note) return;
  
        const report = `
  【爆款笔记拆解报告】
  来源：${note.title}
  作者：${note.author_name}
  分析时间：${new Date().toLocaleString()}
  
  ================================
  
  1. 🎣 钩子 (Hook)
  [${analysis.hook_type}]
  ${analysis.hook_analysis}
  
  2. 🏗️ 结构拆解 (Structure)
  ${analysis.structure_breakdown?.map((s: string, i: number) => `${i+1}. ${s}`).join('\n')}
  
  3. 💖 情绪价值 (Tone)
  ${analysis.tone}
  
  4. 💬 互动策略 (CTA)
  ${analysis.cta_strategy}
  
  5. ✨ 仿写建议 (Remix Tips)
  ${analysis.remix_template}
  
  ================================
  Generated by Little Red Ant AI
  `;
  
        const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `爆款拆解_${note.title.substring(0, 10)}_${Date.now()}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        toast.success('分析报告已导出');
    };

    const handleReAnalyze = async () => {
        if (!onRefreshAnalysis) return;
        setAnalyzing(true);
        try {
            await onRefreshAnalysis(note.note_id || note.id);
        } catch (e) {
            console.error(e);
        } finally {
            setAnalyzing(false);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
            <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
                <div className="p-6">
                    <div className="flex justify-between items-start mb-4">
                        <h3 className="text-xl font-bold text-gray-900 flex items-center">
                            <Sparkles className="inline-block mr-2 text-indigo-600" size={24} />
                            爆款笔记拆解
                        </h3>
                        <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
                            <X size={24} />
                        </button>
                    </div>
                    
                    <div className="space-y-4">
                        <div className="bg-gray-50 p-4 rounded-md">
                            <h4 className="font-medium text-gray-900 mb-2">🎣 钩子 (Hook)</h4>
                            <div className="text-sm text-gray-600">
                                <span className="font-semibold text-indigo-600">[{analysis.hook_type}]</span> {analysis.hook_analysis}
                            </div>
                        </div>

                        {/* Video Player */}
                        {note?.video_url && (
                            <div className="bg-black rounded-md overflow-hidden aspect-video mb-4 relative group">
                                <video 
                                    src={note.video_url} 
                                    controls 
                                    className="w-full h-full"
                                    // @ts-ignore
                                    referrerPolicy="no-referrer"
                                >
                                    您的浏览器不支持视频播放。
                                </video>
                            </div>
                        )}

                        <div className="bg-gray-50 p-4 rounded-md">
                            <h4 className="font-medium text-gray-900 mb-2">🏗️ 结构拆解</h4>
                            <ul className="list-disc list-inside text-sm text-gray-600 space-y-1">
                                {analysis.structure_breakdown?.map((item: string, i: number) => (
                                    <li key={i}>{item}</li>
                                ))}
                            </ul>
                        </div>
                        
                        {/* Video Transcript */}
                        {note?.transcript ? (
                            <div className="bg-amber-50 p-4 rounded-md border border-amber-100">
                                <h4 className="font-medium text-amber-900 mb-2 flex items-center justify-between">
                                    <span>🎙️ 视频口播文案</span>
                                    <span className="text-xs text-amber-700 bg-amber-200/50 px-2 py-0.5 rounded">ASR 转写</span>
                                </h4>
                                <div className="text-sm text-amber-800 max-h-40 overflow-y-auto whitespace-pre-wrap font-mono">
                                    {note.transcript}
                                </div>
                            </div>
                        ) : (
                            note.type === 'video' && (
                                <div className="bg-gray-50 p-3 rounded border border-dashed border-gray-300 text-center text-sm text-gray-500">
                                    该视频暂无口播文案转写
                                </div>
                            )
                        )}

                        <div className="grid grid-cols-2 gap-4">
                            <div className="bg-gray-50 p-4 rounded-md">
                                <h4 className="font-medium text-gray-900 mb-2">🎭 情绪价值</h4>
                                <p className="text-sm text-gray-600">{analysis.tone}</p>
                            </div>
                            <div className="bg-gray-50 p-4 rounded-md">
                                <h4 className="font-medium text-gray-900 mb-2">💬 互动策略</h4>
                                <p className="text-sm text-gray-600">{analysis.cta_strategy}</p>
                            </div>
                        </div>

                        <div className="bg-indigo-50 p-4 rounded-md border border-indigo-100">
                            <h4 className="font-medium text-indigo-900 mb-2">✨ 仿写建议</h4>
                            <p className="text-sm text-indigo-800 whitespace-pre-wrap">{analysis.remix_template}</p>
                        </div>
                    </div>

                    <div className="mt-6 flex justify-end space-x-3 pt-4 border-t border-gray-100">
                        {onRefreshAnalysis && (
                            <button 
                                onClick={handleReAnalyze}
                                disabled={analyzing}
                                className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-md text-sm font-medium flex items-center mr-auto"
                            >
                                <RefreshCw size={16} className={`mr-2 ${analyzing ? 'animate-spin' : ''}`} />
                                {analyzing ? '重新分析中...' : '重新分析'}
                            </button>
                        )}

                        <button 
                            onClick={handleExportAnalysis}
                            className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 flex items-center text-sm font-medium"
                        >
                            <Download size={16} className="mr-2" />
                            导出报告
                        </button>
                        <button 
                            onClick={onClose}
                            className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 text-sm font-medium"
                        >
                            关闭
                        </button>
                        {onSelect && (
                            <button 
                                onClick={() => {
                                    onSelect(note);
                                    onClose();
                                }}
                                className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 flex items-center text-sm font-medium"
                            >
                                <Wand2 size={16} className="mr-2" />
                                使用此结构仿写
                            </button>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default NoteAnalysisModal;